src/apps/accounts/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.views import LogoutView

app_name = 'accounts'

urlpatterns = [
    path('others/actions', OthersActionsList.as_view(), name="other_action"),
    path('login/', login_view, name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("create/", UserCreateView.as_view(), name="create"),
    # USERS
    # path('list/', UserListView.as_view(), name="users_list"),
    # MEMBERS
    path('members/list/', MembersListView.as_view(), name="members_list"),
    path('<int:pk>/update', UserUpdateView.as_view(), name='accounts_update'),
    path('<int:pk>/delete', UserDeleteView.as_view(), name='accounts_delete'),
    path('<int:account_pk>/detail', UserDetailView.as_view(), name='accounts_detail'),

    # REGIONS
    path('region/list', RegionList.as_view(), name="region_list"),
    path('region/create', RegionCreate.as_view(), name="region_create"),
    path('region/detail/<int:pk>', RegionDetail.as_view(), name="region_detail"),
    path('region/<int:pk>/delete', RegionDeleteView.as_view(), name='region_delete'),
    # DEPARTMENTS
    path('department/list', DepartmentListView.as_view(), name="department_list"),
    path('department/create', DepartmentCreate.as_view(), name="department_create"),
    path('department/detail/<int:pk>', DepartmentDetail.as_view(), name="department_detail"),
    path('department/<int:pk>/delete', DepartmentDeleteView.as_view(), name='department_delete'),
    # POSITIONS
    path('position/list', PositionList.as_view(), name="position_list"),
    path('position/create', PositionCreate.as_view(), name="position_create"),
    path('position/detail/<int:pk>', PositionDetail.as_view(), name="position_detail"),
    path('position/<int:pk>/delete', PositionDeleteView.as_view(), name='position_delete'),
    # NATIONS
    path('nation/list', NationList.as_view(), name="nation_list"),
    path('nation/create', NationCreate.as_view(), name="nation_create"),
    path('nation/detail/<int:pk>', NationDetail.as_view(), name="nation_detail"),
    path('nation/<int:pk>/delete', NationDeleteView.as_view(), name='nation_delete'),
    # information
    path('information/list', InformationList.as_view(), name="information_list"),
    path('information/create', InformationCreate.as_view(), name="information_create"),
    path('information/detail/<int:pk>', InformationDetail.as_view(), name="information_detail"),
    path('information/<int:pk>/delete', InformationDeleteView.as_view(), name='information_delete'),

    path('users/create/', UserCreateAction.as_view(), name="create_users"),
    path('region/create/', RegionCreteSerializer.as_view(), name="region_users"),
    path('department/create/', DepartmentCreateSerializer.as_view(), name="department_users"),
    path('user/deparmtnets', UserDepartmentView.as_view(), name="user_departments"),
    path('get/department/by/regions', GetDepartmentByRegion.as_view(), name='get_departments'),  # only AJAX call
    path('get/permission/by/id', GetRolesByID.as_view(), name='get_roles'),  # only AJAX call
]

src/staturmon/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path("accounts/", include('apps.accounts.urls')),
    path("", include("apps.core.urls")),
    path("finance/", include("apps.finance.urls")),
    path("trees/", include("apps.trees.urls")),
    path('agriculture/', include("apps.agriculture.urls")),
    path('chorvachilik/', include("apps.chorvachilik.urls")),
    path('report/', include("apps.report.urls")),
    path('tz_detect/', include('tz_detect.urls')),
    path('api/ipsgov/v1/', include('apps.ipsgov.api.v1.urls')),
    path('ipsgov/', include('apps.ipsgov.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/nation/nation_create.html
{% extends "layouts/base.html" %}
{% load i18n %}
{% block title %} {% trans 'nation create page' %} {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
    {% if perms.accounts.add_nation %}
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <div class="card">
                    <div class="card-header card-header-info py-4 shadow">
                        <h4 class="card-title text-light text-center">{% trans 'nation create form' %}</h4>
                    </div>
                    <div class="card-body mt-4">
                        <form role="form" method="POST" action="{% url 'accounts:nation_create' %}">
                            {% csrf_token %}
                            <div class="row d-flex align-items-end">
                                <div class="col-md-8">
                                    <div class="form-group py-2">
                                        <label for="" class="text-dark">{% trans "Nation name" %}</label>
                                        {{ form.name }}
                                    </div>
                                </div>
                                <div class="col-md-4 d-flex align-items-end">
                                    <button type="submit" class="btn btn-info btn-sm">{% trans 'create' %}</button>
                                    <a href="{% url 'accounts:nation_list' %}"
                                       class="btn btn-success btn-sm text-light">{% trans 'back' %}</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    {% else %}
        <h2>{% trans 'Permission Denied' %}</h2>
    {% endif %}

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
<script>
    let confirmPost = {{state|yesno:"true,false"}}
    if(confirmPost){
        Swal.fire({
          position: 'top-center',
          type: 'success',
          title: '{% trans "Your work has been saved" %}',
          showConfirmButton: false,
          timer: 1000
        })
        setTimeout(() =>{
            location.href="/accounts/nation/list"
        }, 1300)
    }
</script>
{% endblock javascripts %}

src/templates/nation/nation_detail.html
{% extends "layouts/base.html" %}
{% load i18n %}
{% block title %} {% trans 'nation detail page' %} {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
    {% if perms.accounts.view_nation %}
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <div class="card">
                    <div class="card-header card-header-info py-4 shadow">
                        <h4 class="card-title text-light text-center">{% trans 'nation detail form' %}</h4>
                    </div>
                    <div class="card-body mt-4">
                        <form role="form" method="POST" action="{% url 'accounts:nation_detail' nation.id %}">
                            {% csrf_token %}
                            <div class="row d-flex align-items-end">
                                <div class="col-md-8">
                                    <div class="form-group py-2">
                                        <label for="" class="text-dark">{% trans "Nation name" %}</label>
                                        {{ form.name }}
                                    </div>
                                </div>
                                <div class="col-md-12 d-flex align-items-center justify-content-between">
                                    <a href="{% url 'accounts:nation_list' %}"
                                       class="btn btn-success btn-sm text-light">{% trans 'back' %}</a>
                                    {% if perms.accounts.change_nation %}
                                        <button type="submit" class="btn btn-info btn-sm">{% trans 'update' %}</button>
                                    {% endif %}
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

        </div>
    {% else %}
        <h2>{% trans "Permision denied" %}</h2>
    {% endif %}

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

src/templates/nation/nation_list.html
{% extends "layouts/base.html" %}
{% load i18n %}

{% block title %} {% trans 'nation list page title' %} {% endblock %}
<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}
{% trans "This is the title" as the_title %}
{% block content %}
    {% if perms.accounts.view_nation %}
        <div class="row">
            <div class="col-md-12 ">
                <div class="card">
                    <div class="card-header card-header-info py-4 d-flex justify-content-between align-items-center">
                        <div>
                            <h4 class="card-title text-light">{% trans 'nation list' %}</h4>
                            <p class="card-category text-light"></p>
                        </div>
                        <a type="button" class="btn btn-success btn-sm" href="{% url 'accounts:nation_create' %}">
                            {% trans 'create' %}
                        </a>
                    </div>

                    <div class="card-body">
                        <div class="table">
                            <table class="table table-hover table-responsive-xl table-responsive-lg table-responsive-md table-responsive-sm">
                                <thead class=" text-info">
                                <th>{% trans 'id' %}</th>
                                <th>{% trans 'nation name' %}</th>
                                <th>{% trans 'update' %}</th>
                                </thead>
                                <tbody>
                                {% for nation in nations %}
                                    <tr>
                                        <td class="border">{{ nation.id }}</td>
                                        <td class="border">{{ nation.name }}</td>
                                        <td class=" py-2">
                                            {% if perms.accounts.change_nation %}
                                                <a title="{% trans 'edit' %}"
                                                   href="{% url 'accounts:nation_detail' nation.id %}"
                                                   class="btn btn-info btn-fab btn-fab-mini btn-round text-light">
                                                    <i class="material-icons">edit</i></a>
                                            {% endif %}
                                            {% if perms.accounts.delete_nation %}
                                                <a data-toggle="modal" data-target="#removeUser"
                                                   onclick="removeItem({{ nation.id }})"
                                                   class="btn btn-info btn-fab btn-fab-mini btn-round text-light">
                                                    <i class="material-icons">delete</i></a>
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% else %}
        <h1>{% trans 'Permission Denied' %}</h1>
    {% endif %}
    <nav aria-label="Page navigation example ">
        {% if is_paginated %}
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                    <li class="page-item" aria-current="page">
                        <a href="?page={{ page_obj.previous_page_number }}" class="page-link">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                {% else %}
                    <li class="page-item disabled"><a class="page-link" aria-disabled="true">
                        <span aria-hidden="true">&laquo;</span>
                    </a></li>
                {% endif %}
                {% for i in paginator.page_range %}
                    {% if page_obj.number == i %}
                        <li class="page-item active"><a class="page-link" href="#">{{ i }}</a></li>
                    {% else %}
                        <li class="page-item "><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link" disabled="true" href="#">
                            <span aria-hidden="true">&raquo;</span>
                        </a></li>
                {% endif %}
            </ul>
        {% endif %}
    </nav>
    <div class="modal fade" id="removeUser" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">{% trans 'delete' %}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <span>{% trans "Sizni ishonchingiz komilmi?" %}</span>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-success btn-sm" data-dismiss="modal">Close</button>
                    <a href="" class="btn btn-danger btn-sm" id="remove">{% trans 'confirm' %}</a>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
    <script>
        const removeItem = (id) => {
            const anchor = document.querySelector('#remove')
            anchor.href = `/accounts/nation/${id}/delete`
        }
    </script>
{% endblock javascripts %}