src/apps/finance/urls.py
from django.urls import path
from .views import *

app_name = 'finance'

urlpatterns = [
    # FINANCE TYPE
    path('dashboard/', FinanceDashboard.as_view(), name="finance_dashboard"),
    path('list/', FinanceTypeList.as_view(), name="finance_type_list"),
    path('create/', FinanceTypeCreate.as_view(), name="finance_type_create"),
    path('detail/<int:pk>', FinanceTypeDetail.as_view(), name="finance_type_detail"),
    path('type/<int:pk>/delete', FinanceTypeDeleteView.as_view(), name='finance_type_delete'),

    # FINANCE
    path('finance/list', FinanceList.as_view(), name="finance_list"),
    path('finance/create', FinanceCreate.as_view(), name="finance_create"),
    path('finance/detail/<int:pk>', FinanceDetail.as_view(), name="finance_detail"),
    path('finance/<int:pk>/delete', FinanceDeleteView.as_view(), name='finance_delete'),
    path('finance/actual/state/change/', ChangeFinanceActualState.as_view(), name="finance_actual_state_change"),

    # FINANCE PLAN
    path('plan/list', FinancePlanList.as_view(), name="finance_plan_list"),
    path('plan/create', FinancePlanCreate.as_view(), name="finance_plan_create"),
    path('plan/detail/<int:pk>', FinancePlanDetail.as_view(), name="finance_plan_detail"),
    path('plan/<int:pk>/delete', FinancePlanDeleteView.as_view(), name='finance_type_delete'),

    # ProductionServiceActual
    path('production/dashboard', ProductionAndPaidServiceDashboard.as_view(), name="production_dashboard"),
    path('production/actual/list', ProductionServiceActualList.as_view(), name="production_actual_list"),
    path('production/actual/create', ProductionServiceActualCreate.as_view(), name="production_actual_create"),
    path('production/actual/detail/<int:pk>', ProductionServiceActualDetail.as_view(), name="production_actual_detail"),
    path('production/actual/<int:pk>/delete', ProductionServiceActualDeleteView.as_view(), name='production_actual_delete'),

    # ProductionServicePlan
    path('production/plan/list', ProductionServicePlanList.as_view(), name="production_plan_list"),
    path('production/plan/create', ProductionServicePlanCreate.as_view(), name="production_plan_create"),
    path('production/plan/detail/<int:pk>', ProductionServicePlanDetail.as_view(), name="production_plan_detail"),
    path('production/plan/<int:pk>/delete', ProductionServicePlanDeleteView.as_view(), name='production_plan_delete'),

    # Production_Paid_Service_Report
    path('production/service/all/report', ProductServiceAllReport.as_view(), name="production_service_report"),   # excel | prod_service_by_quarter

    #EXPORT CSV
    path('export-csv', export_csv, name="export_csv"),
    path('export-exel', export_exel, name="export_exel"),

    # REPORT
    path('reports/', Report.as_view(), name="report"),  # excel | finance_general
    path('all/report/', AllReport.as_view(), name="all_report"),    # excel | finance_by_quarter
    path('profit/types/report', FinanceProfitTypesReport.as_view(), name="profit_types_report"),  # excel | finance_all_types
    path('existing/sids', ExistingSids.as_view(), name="existing_sids"),

    # Generate EXCEL files
    path("finance/report/by/quarter", FinancePlanQuarterReportXLSX.as_view(), name='finance_by_quarter'),
    path("finance/all/types/report", FinanceByTypeReportXLSX.as_view(), name='finance_all_types'),
    path("finance/general/report", FinanceGeneralReportXLSX.as_view(), name='finance_general'),
    path("prod/services/report/by/quarter", ProductionServicesReportXLSX.as_view(), name='prod_service_by_quarter'),
]

src/staturmon/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path("accounts/", include('apps.accounts.urls')),
    path("", include("apps.core.urls")),
    path("finance/", include("apps.finance.urls")),
    path("trees/", include("apps.trees.urls")),
    path('agriculture/', include("apps.agriculture.urls")),
    path('chorvachilik/', include("apps.chorvachilik.urls")),
    path('report/', include("apps.report.urls")),
    path('tz_detect/', include('tz_detect.urls')),
    path('api/ipsgov/v1/', include('apps.ipsgov.api.v1.urls')),
    path('ipsgov/', include('apps.ipsgov.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/apps/trees/forms.py
from django import forms

from .models import *
from ..accounts.models import Department, Region


class DateInput(forms.DateInput):
    input_type = 'date'


class TreeCategoryForm(forms.ModelForm):
    name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control"
            }
        ))

    class Meta:
        model = TreeCategory
        fields = ('name',)


class TreeTypeForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}))
    show_profit = forms.BooleanField(required=False, initial=False)

    class Meta:
        model = TreeTypes
        fields = ('name', "show_profit")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['show_profit'].widget.attrs.update({
            'class': 'form-check',
        })


class TreePlantForm(forms.ModelForm):
    category = forms.ModelChoiceField(
        queryset=TreeCategory.objects.exclude(status=2),
        to_field_name='name', empty_label="---------"
    )
    name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control"
            }
        ))
    description = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control"
            }
        ))
    is_show_sprouting = forms.BooleanField(required=False)
    is_show_seed = forms.BooleanField(required=False)
    is_show_sapling = forms.BooleanField(required=False)
    is_show_height = forms.BooleanField(required=False)

    class Meta:
        model = TreePlant
        fields = (
            'name', 'description', 'category', "is_show_sprouting", "is_show_seed", "is_show_sapling",
            "is_show_height",)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['description'].required = False
        self.fields['category'].widget.attrs.update({
            'class': 'custom-select',
            'name': 'name',
            'required': False,
        })
        self.fields['category'].required = False
        self.fields['is_show_sprouting'].widget.attrs.update({
            'class': 'form-check'
        })
        self.fields['is_show_seed'].widget.attrs.update({
            'class': 'form-check'
        })
        self.fields['is_show_sapling'].widget.attrs.update({
            'class': 'form-check'
        })
        self.fields['is_show_height'].widget.attrs.update({
            'class': 'form-check'
        })


class TreeHeightForm(forms.ModelForm):
    tree_plan = forms.ModelChoiceField(
        queryset=TreePlant.objects.filter(is_show_height=True, status=1),
        to_field_name='name', empty_label="--------"
    )
    height_0_0_2_count = forms.FloatField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "0,2 м гача",
                "class": "form-control"
            }
        ))
    height_0_2_5_count = forms.FloatField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "0,2 дан 0,5 м гача",
                "class": "form-control"
            }
        ))
    height_0_5_1_count = forms.FloatField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "0,5 -1 м. гача",
                "class": "form-control"
            }
        ))
    height_1_1_5_count = forms.FloatField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "1-1,5 м гача",
                "class": "form-control"
            }
        ))
    height_1_5_2_count = forms.FloatField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "1,5-2 м гача",
                "class": "form-control"
            }
        ))
    date = forms.DateField(widget=DateInput(attrs={
        "class": "form-control"
    }))
    region = forms.ModelChoiceField(
        queryset=Region.objects.filter(status=1),
        to_field_name='name', empty_label="--------"
    )
    department = forms.ModelChoiceField(
        queryset=Department.objects.filter(status=1),
        to_field_name='name', empty_label="---------"
    )

    class Meta:
        model = TreeHeightReport
        fields = ("tree_plan",
                  "height_0_0_2_count",
                  "height_0_2_5_count",
                  "height_0_5_1_count",
                  "height_1_1_5_count",
                  "height_1_5_2_count",
                  "date",
                  "region",
                  "department")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['height_0_0_2_count'].required = False
        self.fields['height_0_2_5_count'].required = False
        self.fields['height_0_5_1_count'].required = False
        self.fields['height_1_1_5_count'].required = False
        self.fields['height_1_5_2_count'].required = False
        self.fields['department'].widget.attrs.update({
            'class': 'form-control',
            'name': 'department',
            'required': 'required',
        })
        self.fields['region'].widget.attrs.update({
            'class': 'form-control',
            'name': 'region',
            'required': 'required',
        })
        self.fields['tree_plan'].widget.attrs.update({
            'class': 'form-control',
            "name": 'tree_plant',
            'required': 'required'
        })


class TreeContractForm(forms.ModelForm):
    category = forms.ModelChoiceField(
        queryset=TreeContractCategory.objects.filter(status=1),
        to_field_name='name', empty_label="--------"
    )
    count = forms.FloatField(
        widget=forms.NumberInput(
            attrs={
                "class": "form-control"
            }
        ))
    amount = forms.FloatField(
        widget=forms.NumberInput(
            attrs={
                "class": "form-control"
            }
        ))
    payout = forms.FloatField(
        widget=forms.NumberInput(
            attrs={
                "class": "form-control"
            }
        ))
    output_tree = forms.FloatField(
        widget=forms.NumberInput(
            attrs={
                "class": "form-control"
            }
        ))
    date = forms.DateField(widget=DateInput(attrs={
        "class": "form-control"
    }))
    region = forms.ModelChoiceField(
        queryset=Region.objects.filter(status=1),
        to_field_name='name', empty_label="--------"
    )
    department = forms.ModelChoiceField(
        queryset=Department.objects.filter(status=1),
        to_field_name='name', empty_label="---------"
    )

    class Meta:
        model = TreeContract
        fields = ("category",
                  "count",
                  "amount",
                  "payout",
                  "output_tree",
                  "date",
                  "region",
                  "department")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['count'].required = False
        self.fields['amount'].required = False
        self.fields['payout'].required = False
        self.fields['output_tree'].required = False
        self.fields['department'].widget.attrs.update({
            'class': 'form-control',
            'name': 'department',
            'required': 'required',
        })
        self.fields['region'].widget.attrs.update({
            'class': 'form-control',
            'name': 'region',
            'required': 'required',
        })
        self.fields['category'].widget.attrs.update({
            'class': 'form-control',
            "name": 'category',
            'required': 'required'
        })


class TreeContractPlanForm(forms.ModelForm):
    tree_count = forms.FloatField(
        widget=forms.NumberInput(
            attrs={
                "class": "form-control"
            }
        ))
    region = forms.ModelChoiceField(
        queryset=Region.objects.filter(status=1),
        to_field_name='name', empty_label="--------"
    )
    department = forms.ModelChoiceField(
        queryset=Department.objects.filter(status=1),
        to_field_name='name', empty_label="---------"
    )

    class Meta:
        model = TreeContractPlan
        fields = ("tree_count",
                  "region",
                  "department")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['tree_count'].required = True
        self.fields['department'].widget.attrs.update({
            'class': 'form-control',
            'name': 'department',
            'required': 'required',
        })
        self.fields['region'].widget.attrs.update({
            'class': 'form-control',
            'name': 'region',
            'required': 'required',
        })


class SaplingForm(forms.ModelForm):
    date = forms.DateField(widget=DateInput(attrs={
        "class": "form-control"
    }))
    count = forms.FloatField(
        widget=forms.NumberInput(
            attrs={
                "placeholder": "Amount",
                "class": "form-control",
                "step": "0.01",
                "min": "0.00"
            }
        ))
    department = forms.ModelChoiceField(
        queryset=Department.objects.filter(status=1),
        to_field_name='name', empty_label="------------"
    )
    region = forms.ModelChoiceField(
        queryset=Region.objects.filter(status=1),
        to_field_name='name', empty_label="------------"
    )
    plant = forms.ModelChoiceField(
        queryset=TreePlant.objects.filter(status=1, is_show_sprouting=True),
        to_field_name='name', empty_label="-------------"
    )

    class Meta:
        model = Sapling
        fields = ('date', 'count', 'department', 'region', 'creator', 'plant')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['department'].widget.attrs.update({

src/templates/moliya/finance_plan/finance_plan_create.html
{% extends "layouts/base.html" %}
{% load i18n %}
{% block title %} {% trans 'report title title' %} {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
    <style>
        #app{
            display: block;
            position: relative;
        }
        .fixed-add-btn{
            position: fixed;
            top:50%;
            left: 85%;
        }
    </style>
{% endblock stylesheets %}
{% block content %}
    {% if perms.finance.add_financeplan %}
        <div class="row"  id="app">
            <div class="col-md-8 offset-md-2">
                <form @submit.prevent="createFinance" id="form">
                    {% csrf_token %}
                    <div class="card">
                        <div class="card-header card-header-info py-4">
                            <h4 class="card-title text-light text-center">{% trans 'Finance create form' %}</h4>
                        </div>
                        <div class="card-body mt-2">
                            <div class="row d-flex align-items-end bg-light border mb-1 mx-1">
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label for="date">{% trans 'Year' %}</label>
                                        <select id="years" class="custom-select" v-model="date">
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label for="region_id">{% trans 'Region' %}</label>
                                        <select name="region" id="region_id" class="custom-select" v-model="region"  @change="regionChangeHandler(region)" required>
                                            <option v-for="(item, index) in regions" :key="item.id" :value="item.id">[[ item.name ]]</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label for="region">{% trans 'Department' %}</label>
                                        <select name="department" id="department_id" class="custom-select" v-model="department" @change="departmentChangeHandler(department)" required>
                                            <option v-for="item in selectedDepartments" :key="item.id" :value="item.id">[[ item.name ]]</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group py-2">
                                        <label for="date" class="text-dark">{% trans 'Yillik' %}</label>
                                        <input type="number" step="0.01" class="form-control" v-model="years" readonly>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="card-body">
                            <div class="row d-flex align-items-end bg-light border mb-1 mx-1">
                                 <div class="col-md-4 pt-2" v-for="(item, i) in months" :key="item">
                                    <div class="form-group py-1">
                                        <label class="text-dark">[[ item ]]</label>
                                        <input type="number" step="0.01"  class="form-control" v-model="income[i].amount" @change="allSum()" required>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-12 d-flex align-items-end justify-content-end">
                            <button type="button" @click="saveAndExit(); createFinance(); " class="btn btn-info btn-sm">{% trans 'save and exit' %}</button>
                            <button type="button" @click="saveAndNext(); createFinance(); " class="btn btn-info btn-sm">{% trans 'save' %}</button>
                            <a href="{% url 'finance:finance_plan_list' %}"
                                class="btn btn-success btn-sm text-light">
                                {% trans 'back' %}
                            </a>
                        </div>
                    </div>
                 </form>
            </div>
        </div>

    {% else %}
        <h2>{% trans 'Permission Denied' %}</h2>
    {% endif %}

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
    <script>
    let department;
    {% if departments is none %}department = null;{% else %} department = {{ departments|safe }};{% endif %}
    if(!department){
        let msg =  "{% trans "Sizda ruxsat yoq Admin bilan boglaning!" %}"
        warningMessage(msg)
        setTimeout(() => {
            location.href = '/finance/plan/list'
        }, 1600)
    }
    let amount_type = {{ amount_type }};
    let region_data = {{ region|safe }};
    const  years = document.querySelector('#years');
    let currentYear = new Date().getFullYear() - 1;
    for(let i = 0; i < 5; i++){
        let opt = document.createElement('option')
        opt.textContent = currentYear++
        years.appendChild(opt)
    }
    const departments = convertToJson(department);
    const token = getCsrfToken(document.querySelectorAll('input'));
    const regions = convertToObj(region_data)
    const app = new Vue({
      delimiters: ['[[', ']]'],
      el: '#app',
      data: {
          count: 1,
          date: null,
          region: null,
          months: ["{% trans 'Январ' %}", "{% trans 'Феврал' %}", "{% trans 'Март' %}", "{% trans 'Апрел' %}",
                    "{% trans 'Май' %}", "{% trans 'Июн' %}", "{% trans 'Июл' %}", "{% trans 'Август' %}",
                    "{% trans 'Сентябр' %}", "{% trans 'Октябр' %}", "{% trans 'Ноябр' %}", "{% trans 'Декабр' %}"],
          department: null,
          income: [
              {amount: null},
              {amount: null},
              {amount: null},
              {amount: null},
              {amount: null},
              {amount: null},
              {amount: null},
              {amount: null},
              {amount: null},
              {amount: null},
              {amount: null},
              {amount: null}
          ],
          years: null,
          next:false,
          regions: regions,
          selectedDepartments: [],
          departmentsRoot: departments,
          token: token

      },
      methods: {
          regionChangeHandler(id){
            this.selectedDepartments = this.departmentsRoot.filter(elem => elem.region === id)
          },
          departmentChangeHandler(id){
              this.department = id
          },
          incrementFormRow(){
              this.count++;
              const obj = {
               amount: null,
               type: ""
             };
             this.income.push(obj)
          },
          removeRow(id){
              this.income.splice(id, 1);
              this.count--
          },
         async createFinance(){
              let form = new FormData();
              form.append("csrfmiddlewaretoken", this.token);
              form.append("date", this.date);
              form.append("region", this.region);
              form.append("department", this.department);
              form.append("amount_type", amount_type);
              form.append("next", this.next);
              form.append("items", JSON.stringify(this.income));
              const url = location.origin + "/finance/plan/create";
              try{
                const response = await fetch(url, {
                    method: 'POST',
                    body: form
                })
                if(!response.redirected && response.status === 201){
                    let msg = "{% trans 'Your work has been saved' %}"
                    successMessage(msg)
                    this.income.forEach(item => item['amount'] = null)
                    this.region = null
                    this.department = null
                    this.years = 0
                } else if(!response.redirected && response.status === 400){
                    let msg = `{% trans 'Bu bolim uchun' %} ${this.date} {% trans 'yilga reja kiritilgan' %}`;
                    warningMessage(msg)
                    this.income.forEach(item => item['amount'] = null)
                    this.region = null
                    this.department = null
                    this.years = 0
                }
                else if(response.redirected){
                    let msg = "{% trans 'Your work has been saved' %}"
                    successMessage(msg)
                    setTimeout(() => {
                        location.href = response.url
                    }, 1500)
                } else {
                    let msg = "{% trans "All fields required.." %}"
                    warningMessage(msg)
                }
              } catch (error) {
                  let msg = "Eroor что пошло не так......"
                  errorMessage(msg)
              }
          },
          allSum(){
              this.years = this.income.reduce( (acc, item) => {
                  if(parseInt(item['amount']) > 0){
                    acc += parseInt(item['amount'])
                  }
                  return acc
                }, 0)
          },
          saveAndNext(){
              this.next = true
          },
          saveAndExit(){
              this.next = false
          }
      },
    });
  </script>
{% endblock javascripts %}

src/templates/moliya/finance_plan/finance_plan_detail.html
{% extends "layouts/base.html" %}
{% load i18n %}
{% block title %} {% trans 'finance plan detail title' %} {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
    {% if perms.finance.view_financeplan %}
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <div class="card">
                    <div class="card-header card-header-info shadow">
                        <h4 class="card-title text-light text-center">{% trans 'finance plan detail form page' %}</h4>
                    </div>
                    <div class="card-body mt-4">
                        <form role="form" method="POST" action="{% url 'finance:finance_plan_detail' finance.id %}">
                            {% csrf_token %}
                            <div class="row d-flex align-items-end">
                                <div class="col-md-4">
                                    <div class="form-group py-2">
                                        <label for="" class="text-dark">{% trans "date" %}</label>
                                        <input type="date" name="date" required class="form-control" id="id_date"
                                               value="{{ form.date.value |date:"Y-m-d" }}">
                                    </div>
                                </div>

                                <div class="col-md-4">
                                    <div class="form-group py-2">
                                        <label for="id_region" class="text-dark">{% trans "Region" %}</label>
                                        {{ form.region }}
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group py-2">
                                        <label for="id_department" class="text-dark">{% trans "Department" %}</label>
                                        {{ form.department }}
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group py-2">
                                        <label for="id_amount" class="text-dark">{% trans "Amount" %}</label>
                                        {{ form.amount }}
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group py-2">
                                        <input name="creator" type="hidden" value="{{ user.pk }}">
                                    </div>
                                </div>

                                <div class="col-md-12 d-flex align-items-end justify-content-between">

                                    <a href="{% url 'finance:finance_plan_list' %}"
                                       class="btn btn-success btn-sm text-light">{% trans 'back' %}</a>
                                    {% if perms.finance.change_financeplan %}

                                        <button type="submit" class="btn btn-info btn-sm">{% trans 'update' %}</button>
                                    {% endif %}
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

        </div>
    {% else %}
        <h2>{% trans 'Permission Denied' %}</h2>
    {% endif %}

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
    <script>
        let d = {{data|safe}};
        let r = {{ region|safe }};
        const region = document.getElementById('id_region');
        const departmentOptions = document.getElementById('id_department');
        const departments = d.map(elem => {
            if (elem) {
                let obj = {name: elem.fields['name'], region: elem.fields['region']}
                return obj
            }
        })
        const regions = r.map(elem => {
            if (elem) {
                let obj = {id: elem.pk, name: elem.fields['name']}
                return obj
            }
        })
        const setDepartment = (city) => {
            const region = regions.find(elem => elem.name === city);
            const current = departments.filter(elem => elem.region === region.id)
            if (current.length > 0) {
                departmentOptions.innerHTML = ""
                current.forEach((elem, index) => {
                    if (elem.name && index === 0) {
                        departmentOptions.innerHTML += `<option value='${elem.name}' selected>${elem.name}</option>`
                    } else if (elem.name) {
                        departmentOptions.innerHTML += `<option value='${elem.name}'>${elem.name}</option>`
                    }
                })
            } else departmentOptions.innerHTML = ""
        }
        region.addEventListener('change', (event) => {
            const city = event.target.value;
            city ? setDepartment(city) : departmentOptions.innerHTML = "";

        })

    </script>
{% endblock javascripts %}