src/apps/chorvachilik/urls.py
from django.urls import path
from .views import *

app_name = 'chorvachilik'

urlpatterns = [
    # Chorvachilik ACTUAL
    path('chorvachilik/actual/list', ChorvachilikActualList.as_view(), name="chorvachilik_actual_list"),
    path('chorvachilik/actual/create/', ChorvachilikActualCreate.as_view(), name="chorvachilik_actual_create"),
    path('chorvachilik/actual/detail/<int:pk>/', ChorvachilikActualDetail.as_view(), name="chorvachilik_actual_detail"),
    path('chorvachilik/actual/<int:pk>/delete', ChorvachilikActualDeleteView.as_view(),
         name="chorvachilik_actual_delete"),

    # chorvachilik PLAN
    path('chorvachilik/plan/list', ChorvachilikPlanList.as_view(), name="chorvachilik_plan_list"),
    path('chorvachilik/plan/create/', ChorvachilikPlanCreate.as_view(), name="chorvachilik_plan_create"),
    path('chorvachilik/plan/detail/<int:pk>/', ChorvachilikPlanDetail.as_view(), name="chorvachilik_plan_detail"),
    path('chorvachilik/plan/<int:pk>/delete', ChorvachilikPlanDeleteView.as_view(), name="chorvachilik_plan_delete"),

    # chorvachilik REPORT
    path('chorvachilik/report/dashboard', ChorvachilikReportDashboardView.as_view(),
         name="chorvachilik_report_dashboard"),
    path('chorvachilik/all/report/', ChorvachilikAllReportsView.as_view(), name="chorvachilik_all_report"),  # excel | chorvachilik_xlsx
    path('chorvachilik/report/region/<int:pk>/', ChorvachilikRegionReport.as_view(), name="chorvachilik_report_region"),
    path('chorvachilik/report/department/<int:pk>/', ChorvachilikDepartmentReport.as_view(),
         name="chorvachilik_report_department"),

    # chorvachilik INPUT
    path('chorvachilik/input/list', ChorvaInputList.as_view(), name="chorva_input_list"),
    path('chorvachilik/input/create/', ChorvaInputCreate.as_view(), name="chorva_input_create"),
    path('chorvachilik/input/detail/<int:pk>/', ChorvaInputDetail.as_view(), name="chorva_input_detail"),
    path('chorvachilik/input/<int:pk>/delete', ChorvaInputDeleteView.as_view(), name="chorva_input_delete"),

    # chorvachilik OUTPUT
    path('chorvachilik/output/list', ChorvaOutputList.as_view(), name="chorva_output_list"),
    path('chorvachilik/output/create/', ChorvaOutputCreate.as_view(), name="chorva_output_create"),
    path('chorvachilik/output/detail/<int:pk>/', ChorvaOutputDetail.as_view(), name="chorva_output_detail"),
    path('chorvachilik/output/<int:pk>/delete', ChorvaOutputDeleteView.as_view(), name="chorva_output_delete"),

    # CHORVA INPUT OUTPUT REPORT
    path("chorva/in/out/report/dashboard", ChorvaInOutDashboard.as_view(), name="chorva_in_out_report_dashboard"),
    path('chorva/in/out/all/report', ChorvaInOutAllReport.as_view(), name="chorva_in_out_all_report"),
    path('chorva/in/out/department/report/<int:pk>', ChorvaInOutDeparmentReport.as_view(),  # excel | chorva_input_output
         name="chorva_in_out_department_report"),

    # ANIMAL
    path('animal/list', AnimalList.as_view(), name="animal_list"),
    path('animal/create/', AnimalCreate.as_view(), name="animal_create"),
    path('animal/detail/<int:pk>/', AnimalDetail.as_view(), name="animal_detail"),
    path('animal/<int:pk>/delete', AnimalDeleteView.as_view(), name="animal_delete"),

    # ANIMAL CATEGORY
    path('view_animalcategory', AnimalCategoryList.as_view(), name="animal_category_list"),
    path('animal/category/create/', AnimalCategoryCreate.as_view(), name="animal_category_create"),
    path('animal/category/detail/<int:pk>/', AnimalCategoryDetail.as_view(), name="animal_category_detail"),
    path('animal/category/<int:pk>/delete', AnimalCategoryDeleteView.as_view(), name="animal_category_delete"),

    # INPUT OUTPUT CATEGORY
    path('in_out/category/list', IoCategoryList.as_view(), name="in_out_category_list"),
    path('in_out/category/create/', IoCategoryCreate.as_view(), name="in_out_category_create"),
    path('in_out/category/detail/<int:pk>/', IoCategoryDetail.as_view(), name="in_out_category_detail"),
    path('in_out/category/<int:pk>/delete', IoCategoryDeleteView.as_view(), name="in_out_category_delete"),

    # CHORVA TYPE
    path('chorva/type/list', ChorvaTypeList.as_view(), name="chorva_type_list"),
    path('chorva/type/create/', ChorvaTypeCreate.as_view(), name="chorva_type_create"),
    path('chorva/type/detail/<int:pk>/', ChorvaTypeDetail.as_view(), name="chorva_type_detail"),
    path('chorva/type/<int:pk>/delete', ChorvaTypeDeleteView.as_view(), name="chorva_type_delete"),

    # CHORVA CATEGORY ChorvaCategoryDetail
    path('chorva/category/list', ChorvaCategoryList.as_view(), name="chorva_category_list"),
    path('chorva/category/create/', ChorvaCategoryCreate.as_view(), name="chorva_category_create"),
    path('chorva/category/detail/<int:pk>/', ChorvaCategoryDetail.as_view(), name="chorva_category_detail"),
    path('chorva/category/<int:pk>/delete', ChorvaCategoryDeleteView.as_view(), name="chorva_category_delete"),

    # Generate EXCEL files
    path("chorva/report/by/animal", ChorvachilikXLSX.as_view(), name='chorvachilik_xlsx'),
    path("chorva/inp/out/report", ChorvaInputOutputXLSX.as_view(), name='chorva_input_output'),

    path('chorva/upload/file/', UploadFIleAPIView.as_view(), name="file_upload"),
    path('chorva/delete/file/<int:pk>', UploadFIleDeleteAPIView.as_view(), name="file_delete")
]

src/staturmon/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path("accounts/", include('apps.accounts.urls')),
    path("", include("apps.core.urls")),
    path("finance/", include("apps.finance.urls")),
    path("trees/", include("apps.trees.urls")),
    path('agriculture/', include("apps.agriculture.urls")),
    path('chorvachilik/', include("apps.chorvachilik.urls")),
    path('report/', include("apps.report.urls")),
    path('tz_detect/', include('tz_detect.urls')),
    path('api/ipsgov/v1/', include('apps.ipsgov.api.v1.urls')),
    path('ipsgov/', include('apps.ipsgov.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/apps/chorvachilik/models.py
from django.db import models

from ..accounts.models import Department, STATES_STATUSES, User, Region
from ..core.models import TimestampedModel

AMOUNT_TYPES = (
    (1, "PCS"),
    (2, "KG"),
    (3, "HEAD"),
    (4, "TON"),
    (5, "FAMILY"),
)
STATUS = ((1, "NEW"), (2, "CONFIRM"), (3, "DELETE"))
INPUT_OUTPUT_TYPES = ((1, "INPUT"), (2, "OUTPUT"))


class ChorvachilikTypes(TimestampedModel):
    name = models.CharField(max_length=256, blank=True, null=True)
    description = models.CharField(max_length=256, blank=True, null=True)
    status = models.IntegerField(choices=STATES_STATUSES, default=1)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'chorvachilik_types'
        verbose_name_plural = "ChorvachilikType"


class Chorvachilik(TimestampedModel):
    name = models.CharField(max_length=128, blank=True, null=True)
    type = models.ManyToManyField(ChorvachilikTypes, related_name="chorvachilik_type", blank=True)
    show_yield_area = models.BooleanField(default=False)
    profit = models.BooleanField(default=False)
    status = models.IntegerField(choices=STATES_STATUSES, default=1)
    parent = models.ForeignKey('self', related_name='child_chorva', on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return f"{self.name}"

    def get_type(self):
        return " | ".join(item.name for item in self.type.all())

    class Meta:
        db_table = "chorvachilik"
        verbose_name_plural = "Chorvachilik"


class ChorvachilikPlan(TimestampedModel):
    date = models.DateField()
    chorvachilik_type = models.ForeignKey(ChorvachilikTypes, on_delete=models.CASCADE,
                                          related_name="chorvachilik_plan_type", blank=True, null=True)
    chorvachilik = models.ForeignKey(Chorvachilik, on_delete=models.CASCADE,
                                     related_name="chorvachilik_plan_chorvachilik", blank=True, null=True)
    amount = models.FloatField(blank=True, null=True, verbose_name="Amount")
    department = models.ForeignKey(Department, on_delete=models.CASCADE, related_name="chorvachilik_plan_department")
    region = models.ForeignKey(Region, on_delete=models.CASCADE, related_name="chorvachilik_plan_region")
    creator = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="chorvachilik_plan_creator", blank=True, null=True)
    amount_type = models.IntegerField(choices=AMOUNT_TYPES, default=1)
    status = models.IntegerField(choices=STATES_STATUSES, default=1)

    def __str__(self):
        return f'ID: {self.id}'

    class Meta:
        db_table = "chorvachilik_plan"
        verbose_name_plural = "ChorvachilikPlan"


class ChorvachilikActual(TimestampedModel):
    date = models.DateField()
    chorvachilik = models.ForeignKey(Chorvachilik, on_delete=models.CASCADE,
                                     related_name="chorvachilik_actual_chorvachilik", blank=True,
                                     null=True)
    chorvachilik_type = models.ForeignKey(ChorvachilikTypes, on_delete=models.CASCADE,
                                          related_name="chorvachilik_actual_type", blank=True,
                                          null=True)
    amount = models.FloatField(blank=True, null=True, verbose_name="Amount")
    profit = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    department = models.ForeignKey(Department, on_delete=models.CASCADE, related_name="chorvachilik_actual_department")
    region = models.ForeignKey(Region, on_delete=models.CASCADE, related_name="chorvachilik_actual_region")
    creator = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="chorvachilik_actual_creator", blank=True, null=True)
    amount_type = models.IntegerField(choices=AMOUNT_TYPES, default=1)
    status = models.IntegerField(choices=STATES_STATUSES, default=1)

    def __int__(self):
        return self.id

    class Meta:
        db_table = "chorvachilik_actual"
        verbose_name_plural = "ChorvachilikActual"


class AnimalCategory(TimestampedModel):
    name = models.CharField(max_length=120, verbose_name="Animal")
    status = models.IntegerField(choices=STATES_STATUSES, default=1)

    def __str__(self):
        return self.name

    class Meta:
        db_table = "animal_category"
        verbose_name_plural = "AnimalCategory"


class Animal(TimestampedModel):
    name = models.CharField(max_length=120, verbose_name="Animal")
    category = models.ForeignKey(AnimalCategory, on_delete=models.CASCADE, related_name="animal_category", null=True,
                                 blank=True)
    status = models.IntegerField(choices=STATES_STATUSES, default=1)

    def __str__(self):
        return self.name

    class Meta:
        db_table = "animal"
        verbose_name_plural = "Animal"


class ChorvaInputOutputCategory(TimestampedModel):
    name = models.CharField(max_length=256, verbose_name="Kirim yoki chiqim category")
    type = models.IntegerField(choices=INPUT_OUTPUT_TYPES, default=1)
    status = models.IntegerField(choices=STATES_STATUSES, default=1)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'chorva_input_output_category'
        verbose_name_plural = "ChorvaInputOutputCategory"


class ChorvaInputOutput(TimestampedModel):
    date = models.DateField()
    category = models.ForeignKey(ChorvaInputOutputCategory, on_delete=models.CASCADE, blank=True, null=True)
    amount = models.IntegerField(blank=True, null=True, verbose_name="Boshi")
    weight = models.FloatField(blank=True, null=True, verbose_name="Vazni")
    type = models.IntegerField(choices=INPUT_OUTPUT_TYPES, default=1)
    animal = models.ForeignKey(Animal, on_delete=models.CASCADE)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    region = models.ForeignKey(Region, on_delete=models.CASCADE)
    creator = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    status = models.IntegerField(choices=STATUS, default=1)

    def __int__(self):
        return self.id

    class Meta:
        db_table = "chorva_input_output"
        verbose_name_plural = "ChorvaInputOutput"


class UploadFile(TimestampedModel):
    name = models.CharField(max_length=256, null=True, blank=True)
    file = models.FileField(upload_to='output/', null=True, blank=True)
    output = models.ForeignKey(ChorvaInputOutput, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return f"{self.file}"

    def image_tag(self):
        from django.utils.html import mark_safe
        img = mark_safe(f"<img src='{self.file.url}' width='250' />")
        return img

    class Meta:
        db_table = "upload_file"
        verbose_name_plural = "UploadFile"

src/templates/chorvachilik/chorva_category/create.html
{% extends "layouts/base.html" %}
{% load i18n %}
{% block title %} {% trans 'Type create page' %} {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
    {% if perms.chorvachilik.add_chorvachilik %}
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <div class="card">
                    <div class="card-header card-header-info py-4 shadow">
                        <h4 class="card-title text-light text-center">{% trans 'Type create form' %}</h4>
                    </div>
                    <div class="card-body mt-4">
                        <form role="form" method="POST" action="{% url 'chorvachilik:chorva_category_create' %}">
                            {% csrf_token %}
                            <div class="row d-flex align-items-end">
                                <div class="col-md-4">
                                    <div class="form-group py-2">
                                        <label for="" class="text-dark">{% trans "Category name" %}</label>
                                        {{form.name}}
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group py-2">
                                        <label for="" class="text-dark">{% trans "Category type" %}</label>
                                        {{form.type}}
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group py-2">
                                        <label for="" class="text-dark">{% trans "Xosilga kirgan" %}</label>
                                        {{form.show_yield_area}}
                                    </div>
                                </div>
                                <div class="col-md-12 d-flex align-items-end justify-content-between">
                                    <a href="{% url 'chorvachilik:chorva_category_list' %}"
                                    class="btn btn-success btn-sm text-light">{% trans 'back' %}</a>
                                    <button type="submit" class="btn btn-info btn-sm">{% trans 'create' %}</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

        </div>
    {% else %}
        <h2>{% trans "permision_denied" %}</h2>
    {% endif %}

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

src/templates/chorvachilik/chorva_category/detail.html
{% extends "layouts/base.html" %}
{% load i18n %}
{% block title %} {% trans 'Chorva category detail page' %} {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
    {% if not permission_denied %}
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <div class="card">
                    <div class="card-header card-header-info py-4 shadow">
                        <h4 class="card-title text-light text-center">{% trans 'Chorva category detail form' %}</h4>
                    </div>
                    <div class="card-body mt-4">
                        <form role="form" method="POST" action="{% url 'chorvachilik:chorva_category_detail' category.id %}">
                            {% csrf_token %}
                            <div class="row d-flex align-items-end">
                                <div class="col-md-4">
                                    <div class="form-group py-2">
                                        <label for="" class="text-dark">{% trans "Category name" %}</label>
                                        {{form.name}}
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group py-2">
                                        <label for="" class="text-dark">{% trans "Category type" %}</label>
                                        {{form.type}}
                                    </div>
                                </div>
                                <div class="col-md-12 d-flex align-items-end justify-content-between">
                                    <a href="{% url 'chorvachilik:chorva_category_list' %}"
                                     class="btn btn-success btn-sm text-light">{% trans 'back' %}</a>
                                        {% if perms.chorvachilik.change_chorvachilik %}

                                    <button type="submit" class="btn btn-info btn-sm">{% trans 'update' %}</button>
                                            {% endif %}
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

        </div>
    {% else %}
        <h2>{% trans "permision_denied" %}</h2>
    {% endif %}

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

src/templates/chorvachilik/chorva_category/list.html
{% extends "layouts/base.html" %}
{% load i18n %}

{% block title %} {% trans 'Type title' %} {% endblock %}
<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}
{% trans "This is the title" as the_title %}
{% block content %}
    {% if perms.chorvachilik.view_chorvachilik %}
        <div class="row">
            <div class="col-md-12 ">
                <div class="card">
                    <div class="card-header card-header-info py-4 d-flex justify-content-between align-items-center">
                        <div>
                            <h4 class="card-title text-light">{% trans 'Chorva Category list' %}</h4>
                            <p class="card-category text-light"></p>
                        </div>
                        <a type="button" class="btn btn-success btn-sm"
                           href="{% url 'chorvachilik:chorva_category_create' %}">
                            {% trans 'create' %}
                        </a>
                    </div>

                    <div class="card-body">
                        <div class="table">
                            <table class="table table-hover table-responsive-xl table-responsive-lg table-responsive-md table-responsive-sm">
                                <thead class=" text-info">
                                <th>{% trans 'id' %}</th>
                                <th>{% trans 'name' %}</th>
                                <th>{% trans 'type' %}</th>
                                <th>{% trans 'Actions' %}</th>
                                </thead>
                                <tbody>
                                {% for item in items %}
                                    <tr>
                                        <td class="border">{{ item.id }}</td>
                                        <td class="border">{{ item.name }}</td>
                                        <td class="border">[
                                            {% if item.type %}
                                                {% for obj in item.type.all %}
                                                    {{ obj.name }},
                                                {% endfor %}
                                            {% endif %}
                                            ]
                                        </td>
                                        <td class="border">
                                            <a
                                                    href="{% url 'chorvachilik:chorva_category_detail' item.id %}"
                                                    class="btn btn-info btn-fab btn-fab-mini btn-round text-light">
                                                <i class="material-icons">edit</i>
                                            </a>
                                                {% if perms.chorvachilik.delete_chorvachilik %}

                                            <a
                                                    data-toggle="modal"
                                                    data-target="#removeUser"
                                                    onclick="removeItem({{ item.id }})"
                                                    class="btn btn-info btn-fab btn-fab-mini btn-round text-light">
                                                <i class="material-icons">delete</i>
                                            </a>
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% else %}
        <h1>{% trans "Permission Denied" %}</h1>
    {% endif %}
    <nav aria-label="Page navigation example text-center" class="d-flex align-items-center justify-content-center">
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                        <span class="sr-only">begin</span>
                    </a>
                </li>
            {% endif %}
            {% for n in page_obj.paginator.page_range %}
                {% if page_obj.number == n %}
                    <li class="page-item active">
                        <span class="page-link">{{ n }}<span class="sr-only">(current)</span></span>
                    </li>
                {% elif n > page_obj.number|add:'-3' and n < page_obj.number|add:'3' %}
                    <li class="page-item"><a class="page-link" href="?page={{ n }}">{{ n }}</a></li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                        <span class="sr-only">end</span>
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
    <div class="modal fade" id="removeUser" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">{% trans 'delete' %}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <span>{% trans "Sizni ishonchingiz komilmi?" %}</span>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-success btn-sm" data-dismiss="modal">Close</button>
                    <a href="" class="btn btn-danger btn-sm" id="remove">{% trans 'confirm' %}</a>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
    <script>
        const removeItem = (id) => {
            const anchor = document.querySelector('#remove')
            anchor.href = `/chorvachilik/chorva/category/${id}/delete`
        }
    </script>
{% endblock javascripts %}