src/apps/finance/urls.py
from django.urls import path
from .views import *

app_name = 'finance'

urlpatterns = [
    # FINANCE TYPE
    path('dashboard/', FinanceDashboard.as_view(), name="finance_dashboard"),
    path('list/', FinanceTypeList.as_view(), name="finance_type_list"),
    path('create/', FinanceTypeCreate.as_view(), name="finance_type_create"),
    path('detail/<int:pk>', FinanceTypeDetail.as_view(), name="finance_type_detail"),
    path('type/<int:pk>/delete', FinanceTypeDeleteView.as_view(), name='finance_type_delete'),

    # FINANCE
    path('finance/list', FinanceList.as_view(), name="finance_list"),
    path('finance/create', FinanceCreate.as_view(), name="finance_create"),
    path('finance/detail/<int:pk>', FinanceDetail.as_view(), name="finance_detail"),
    path('finance/<int:pk>/delete', FinanceDeleteView.as_view(), name='finance_delete'),
    path('finance/actual/state/change/', ChangeFinanceActualState.as_view(), name="finance_actual_state_change"),

    # FINANCE PLAN
    path('plan/list', FinancePlanList.as_view(), name="finance_plan_list"),
    path('plan/create', FinancePlanCreate.as_view(), name="finance_plan_create"),
    path('plan/detail/<int:pk>', FinancePlanDetail.as_view(), name="finance_plan_detail"),
    path('plan/<int:pk>/delete', FinancePlanDeleteView.as_view(), name='finance_type_delete'),

    # ProductionServiceActual
    path('production/dashboard', ProductionAndPaidServiceDashboard.as_view(), name="production_dashboard"),
    path('production/actual/list', ProductionServiceActualList.as_view(), name="production_actual_list"),
    path('production/actual/create', ProductionServiceActualCreate.as_view(), name="production_actual_create"),
    path('production/actual/detail/<int:pk>', ProductionServiceActualDetail.as_view(), name="production_actual_detail"),
    path('production/actual/<int:pk>/delete', ProductionServiceActualDeleteView.as_view(), name='production_actual_delete'),

    # ProductionServicePlan
    path('production/plan/list', ProductionServicePlanList.as_view(), name="production_plan_list"),
    path('production/plan/create', ProductionServicePlanCreate.as_view(), name="production_plan_create"),
    path('production/plan/detail/<int:pk>', ProductionServicePlanDetail.as_view(), name="production_plan_detail"),
    path('production/plan/<int:pk>/delete', ProductionServicePlanDeleteView.as_view(), name='production_plan_delete'),

    # Production_Paid_Service_Report
    path('production/service/all/report', ProductServiceAllReport.as_view(), name="production_service_report"),   # excel | prod_service_by_quarter

    #EXPORT CSV
    path('export-csv', export_csv, name="export_csv"),
    path('export-exel', export_exel, name="export_exel"),

    # REPORT
    path('reports/', Report.as_view(), name="report"),  # excel | finance_general
    path('all/report/', AllReport.as_view(), name="all_report"),    # excel | finance_by_quarter
    path('profit/types/report', FinanceProfitTypesReport.as_view(), name="profit_types_report"),  # excel | finance_all_types
    path('existing/sids', ExistingSids.as_view(), name="existing_sids"),

    # Generate EXCEL files
    path("finance/report/by/quarter", FinancePlanQuarterReportXLSX.as_view(), name='finance_by_quarter'),
    path("finance/all/types/report", FinanceByTypeReportXLSX.as_view(), name='finance_all_types'),
    path("finance/general/report", FinanceGeneralReportXLSX.as_view(), name='finance_general'),
    path("prod/services/report/by/quarter", ProductionServicesReportXLSX.as_view(), name='prod_service_by_quarter'),
]

src/apps/report/urls.py
from django.urls import path
from .views import *

app_name = 'report'

urlpatterns = [
    path('report/list/', ReportList.as_view(), name="report_list"),
    path('report/create/', ReportCreate.as_view(), name='report_create'),
    path('report/detail/list/', ReportDetailView.as_view(), name="report_detail_list"),
    path('report/hisobot/<int:pk>', ReportPageView.as_view(), name="hisobot"),
    path('report/value/delete/<int:pk>', ReportValueDelete.as_view(), name="report_value_delete"),
    path('query/create', CreateReportQuery.as_view(), name="query_create"),
    path('keys/list/<int:pk>', ResponseReportKeys.as_view(), name="keys_list"),
    path('create/group', CreateReportGroup.as_view(), name='create_report_group'),
    path('create/new/report', CreateNewReport.as_view(), name='create_new_report'),
    path("report/update", UpdateReport.as_view(), name="update_report"),
    #GET LISTED REPORT VALUES
    path('get/listed/values', get_listed_report_values, name='get_listed_report_values'),
    # Generate EXCEL files
    path("general/dynamic/xlsx", GeneralDynamicReportXLSX.as_view(), name='general_dynamic_xlsx'),  # test
]

src/staturmon/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path("accounts/", include('apps.accounts.urls')),
    path("", include("apps.core.urls")),
    path("finance/", include("apps.finance.urls")),
    path("trees/", include("apps.trees.urls")),
    path('agriculture/', include("apps.agriculture.urls")),
    path('chorvachilik/', include("apps.chorvachilik.urls")),
    path('report/', include("apps.report.urls")),
    path('tz_detect/', include('tz_detect.urls')),
    path('api/ipsgov/v1/', include('apps.ipsgov.api.v1.urls')),
    path('ipsgov/', include('apps.ipsgov.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/moliya/dashboard.html
{% extends "layouts/base.html" %}
{% load i18n %}
{% block title %} {% trans "Moliyaviy hisobotlar title" %} {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
<style>
        .card-body {
            display: flex;
            flex-direction: column;
            flex-wrap: wrap;
            justify-content: space-between;
            align-items: flex-end;
        }

        .card-body .card-title {
            text-overflow: ellipsis;
            overflow: hidden;
            white-space: nowrap;
            width: 100%;
            max-width: 100%;
            -webkit-line-clamp: 3;
        }

</style>
{% endblock stylesheets %}
{% block content %}
  <div class="container-fluid">
      <div class="row d-flex justify-content-start align-items-baseline">
          <div class="col-md-12">
              <h2 class="text-center m-0">{% trans "Moliyaviy hisobotlar" %}</h2>
          </div>
{#          <div class="col-lg-3 col-md-4 col-sm-6">#}
{#              <div class="card">#}
{#                  <div class="card-body text-right">#}
{#                        <h4 class="card-title text-center py-3 font-weight-bold">{% trans "Umumiy hisobot" %}</h4>#}
{#                        <a href="{% url 'finance:report' %}?start={{ start }}&end={{ end }}&type=1" class="btn btn-info btn-sm">{% trans "Кириш" %}</a>#}
{#                  </div>#}
{#              </div>#}
{#          </div>#}
{#          <div class="col-lg-3 col-md-4 col-sm-6">#}
{#              <div class="card">#}
{#                  <div class="card-body text-right">#}
{#                        <h4 class="card-title text-center py-3 font-weight-bold">{% trans "Kunlik daromad" %}</h4>#}
{#                        <a href="{% url 'finance:all_report' %}?start={{ start }}&end={{ end }}&type=1" class="btn btn-info btn-sm">{% trans "Кириш" %}</a>#}
{#                  </div>#}
{#              </div>#}
{#          </div>#}
{#          <div class="col-lg-3 col-md-4 col-sm-6">#}
{#              <div class="card">#}
{#                  <div class="card-body text-right">#}
{#                        <h4 class="card-title text-center py-3 font-weight-bold">{% trans "Daromad turlari" %}</h4>#}
{#                        <a href="{% url 'finance:profit_types_report' %}?start={{ start }}&end={{ end }}" class="btn btn-info btn-sm">{% trans "Кириш" %}</a>#}
{#                  </div>#}
{#              </div>#}
{#          </div>#}
            <div class="col-lg-6 col-md-6 col-sm-10">
                <div class="card bg-white p-2 border-top border-primary">
                    <div class="card-header border-bottom d-flex justify-content-between align-items-baseline">
                        <h4 class="text-dark card-title">
                            <span id="finance_year"></span> {% trans "yil reja va amalda" %}
                            &nbsp; {% trans "ming(so'mda)" %}
                        </h4>
                        <a href="{% url 'finance:report' %}?start={{ start }}&end={{ end }}&type=1"
                           class="btn btn-outline-info btn-sm text-dark">{% trans "Batafsil" %}</a>
                    </div>
                    <canvas id="myChart" style="width: 100%; height: 350px;"></canvas>
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-10">
                <div class="card bg-white p-2 border-top border-primary">
                    <div class="card-header border-bottom d-flex justify-content-between align-items-center">
                        <h4 class="text-dark card-title">
                            {% trans "Kunlik tushim" %} <span id="current_month"></span> {% trans "oyi uchun." %}
                            &nbsp; {% trans "ming(so'mda)" %}
                        </h4>
                        <a href="{% url 'finance:all_report' %}?start={{ start }}&end={{ end }}&type=1"
                           class="btn btn-outline-info btn-sm text-dark">{% trans "Batafsil" %}</a>
                    </div>
                    <canvas id="myLineChart" style="width: 100%; height: 350px;"></canvas>
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-10">
                <div class="card bg-white p-2 border-top border-primary">
                    <div class="card-header border-bottom d-flex justify-content-between align-items-center">
                        <h4 class="text-dark card-title">
                            {% trans "Daromad turlari bo'yicha" %} <span id="pia_month"></span> {% trans "oyi uchun." %}
                            &nbsp;{% trans "ming(so'mda)" %}
                        </h4>
                        <a href="{% url 'finance:profit_types_report' %}?start={{ start }}&end={{ end }}&type=1"
                           class="btn btn-outline-info btn-sm text-dark">{% trans "Batafsil" %}</a>
                    </div>
                    <canvas id="mypiechart" style="width: 100%; height: 350px;"></canvas>
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-10">
              <div class="row">
                  {% for item in data %}
                      <div class="col-lg-12">
                          <div class="card bg-white border-top border-primary">
                              <div class="card-header border-bottom d-flex justify-content-between align-items-center">
                                  <h4 class="text-dark card-title">
                                      {{ current_year }} {{ item.name }}
                                  </h4>
                                  <a href="{% url 'report:hisobot' item.id %}"
                                     class="btn btn-outline-info btn-sm text-dark">{% trans "Batafsil" %}</a>
                              </div>
                          </div>
                      </div>
                  {% endfor %}
              </div>
            </div>
      </div>
  </div>
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
    <script>
        function daysInThisMonth() {
          let now = new Date();
          return new Date(now.getFullYear(), now.getMonth()+1, 0).getDate();
        }
        let daysInCurrentMonthCount = daysInThisMonth();
        let months_days = []
        for(let i =1; i <= daysInCurrentMonthCount; i++){
            months_days.push(i)
        }
        const months = ["{% trans 'Январ' %}", "{% trans 'Феврал' %}", "{% trans 'Март' %}", "{% trans 'Апрел' %}",
                        "{% trans 'Май' %}", "{% trans 'Июн' %}", "{% trans 'Июл' %}", "{% trans 'Август' %}",
                        "{% trans 'Сентябр' %}", "{% trans 'Октябр' %}", "{% trans 'Ноябр' %}", "{% trans 'Декабр' %}"]
        document.querySelector('#current_month').textContent = months[new Date().getMonth()]
        document.querySelector('#pia_month').textContent = months[new Date().getMonth()]
        document.querySelector('#finance_year').textContent = new Date().getFullYear();
        let ctx = document.getElementById('myChart');
        let myLineChart = document.querySelector('#myLineChart');
        let myChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: months,
                datasets: [{
                    label: "{% trans 'Reja' %}",
                    data: {% if plan_year %} {{ plan_year }} {% else %} [] {% endif %},
                    backgroundColor: 'rgba(134, 219, 219)',
                    borderColor: 'rgba(134, 219, 210)',
                    borderWidth: 1
                },
                {
                    label: '"{% trans 'Amalda' %}"',
                    data: {% if actual_year %} {{ actual_year }}{% else %} [] {% endif %},
                    backgroundColor: 'rgba(137, 134, 219)',
                    borderColor: 'rgba(134, 219, 210)',
                    borderWidth: 1
            }]
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true
                        }
                    }]
                },
                animation: {
                    duration: 2000
                }
            }
        });
        let myLineChart2 = new Chart(myLineChart, {
            type: 'line',
            data: {
                labels: months_days,
                datasets: [{
                    label: "{% trans 'Amalda' %}",
                    data: {% if actual_month %} {{ actual_month }} {% else %} [] {% endif %},
                    backgroundColor: 'rgba(137, 134, 219, 0.8)',
                    borderColor: 'rgba(137, 134, 219)',
                    borderWidth: 3}
                ]
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true
                        }
                    }]
                },
                animation: {
                    duration: 3000
                }
            }
        });
        let financeTypesNames = {% if finance_types %} {{ finance_types|safe }} {% else %} [] {% endif %}
        let finance_type_names
        if(financeTypesNames){
            finance_type_names = financeTypesNames.map(item => item.fields['name'])
        }
        let myPie = document.querySelector('#mypiechart');
        let internalData = [300, 50, 100, 75];

        let graphColors = [];
        let graphOutlines = [];
        let hoverColor = [];

        let internalDataLength = finance_type_names.length;
        i = 0;
        while (i <= internalDataLength) {
            let randomR = Math.floor((Math.random() * 130) + 100);
            let randomG = Math.floor((Math.random() * 130) + 100);
            let randomB = Math.floor((Math.random() * 130) + 100);

            let graphBackground = "rgb("
                    + randomR + ", "
                    + randomG + ", "
                    + randomB + ")";
            graphColors.push(graphBackground);

            let graphOutline = "rgb("
                    + (randomR - 80) + ", "
                    + (randomG - 80) + ", "
                    + (randomB - 80) + ")";
            graphOutlines.push(graphOutline);

            let hoverColors = "rgb("
                    + (randomR + 25) + ", "
                    + (randomG + 25) + ", "
                    + (randomB + 25) + ")";
            hoverColor.push(hoverColors);

          i++;
        }
        let data = {
            labels: finance_type_names,
            datasets: [{
                data: {% if actual_types %} {{ actual_types }} {% else %} [10,10,10] {% endif %},
                backgroundColor: graphColors,
                hoverBackgroundColor: hoverColor,
                borderColor: graphOutlines
            }]
        };
        let options = {
            cutoutPercentage: 25,
            responsive: true
        };
       let myPieChart = new Chart(myPie, {
            type: 'doughnut',
            data: data,
           options: {
                responsive: true,
                legend: {
                    position: "right",
                    align: "center"
                },
           }
        });
    </script>
{% endblock javascripts %}